# Generated by Django 5.2 on 2026-04-07 13:15

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatConversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('type', models.CharField(choices=[('direct', '单聊'), ('group', '群聊')], max_length=20)),
                ('name', models.CharField(blank=True, default='', max_length=150)),
                ('avatar', models.CharField(blank=True, default='', max_length=500)),
                ('direct_pair_key', models.CharField(blank=True, default=None, max_length=64, null=True, unique=True)),
                ('status', models.CharField(choices=[('active', '正常'), ('disbanded', '已解散')], default='active', max_length=20)),
                ('last_message_preview', models.CharField(blank=True, default='', max_length=255)),
                ('last_message_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('member_count_cache', models.IntegerField(default=0)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_chat_conversations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'chat_conversation',
                'ordering': ['-last_message_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ChatFriendRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pair_key', models.CharField(db_index=True, max_length=64)),
                ('status', models.CharField(choices=[('pending', '待处理'), ('accepted', '已通过'), ('rejected', '已拒绝'), ('canceled', '已取消'), ('expired', '已过期')], default='pending', max_length=20)),
                ('request_message', models.CharField(blank=True, default='', max_length=255)),
                ('auto_accepted', models.BooleanField(default=False)),
                ('handled_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_chat_friend_requests', to=settings.AUTH_USER_MODEL)),
                ('handled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handled_chat_friend_requests', to=settings.AUTH_USER_MODEL)),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_chat_friend_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'chat_friend_request',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='ChatFriendship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pair_key', models.CharField(max_length=64, unique=True)),
                ('status', models.CharField(choices=[('active', '有效'), ('deleted', '已删除')], default='active', max_length=20)),
                ('accepted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('source_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='friendships', to='chat.chatfriendrequest')),
                ('user_high', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_friendships_high', to=settings.AUTH_USER_MODEL)),
                ('user_low', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_friendships_low', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'chat_friendship',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='ChatGroupConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('join_approval_required', models.BooleanField(default=False)),
                ('allow_member_invite', models.BooleanField(default=True)),
                ('max_members', models.IntegerField(blank=True, default=None, null=True)),
                ('mute_all', models.BooleanField(default=False)),
                ('conversation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='group_config', to='chat.chatconversation')),
            ],
            options={
                'db_table': 'chat_group_config',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ChatGroupJoinRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('request_type', models.CharField(choices=[('invite', '邀请')], default='invite', max_length=20)),
                ('status', models.CharField(choices=[('pending', '待处理'), ('approved', '已通过'), ('rejected', '已拒绝'), ('canceled', '已取消'), ('expired', '已过期')], default='pending', max_length=20)),
                ('review_note', models.CharField(blank=True, default='', max_length=255)),
                ('reviewed_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='join_requests', to='chat.chatconversation')),
                ('inviter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_chat_group_join_requests', to=settings.AUTH_USER_MODEL)),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_chat_group_join_requests', to=settings.AUTH_USER_MODEL)),
                ('target_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='targeted_chat_group_join_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'chat_group_join_request',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sequence', models.BigIntegerField()),
                ('message_type', models.CharField(choices=[('text', '文本'), ('system', '系统'), ('image', '图片'), ('file', '文件')], default='text', max_length=20)),
                ('content', models.TextField(blank=True, default='')),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('client_message_id', models.CharField(blank=True, default=None, max_length=64, null=True, unique=True)),
                ('is_system', models.BooleanField(default=False)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chat.chatconversation')),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_chat_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'chat_message',
                'ordering': ['sequence', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ChatConversationMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(choices=[('owner', '群主'), ('admin', '管理员'), ('member', '成员')], default='member', max_length=20)),
                ('status', models.CharField(choices=[('active', '正常'), ('left', '已退出'), ('removed', '已移除')], default='active', max_length=20)),
                ('joined_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('left_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('removed_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('mute_until', models.DateTimeField(blank=True, default=None, null=True)),
                ('mute_reason', models.CharField(blank=True, default='', max_length=255)),
                ('is_pinned', models.BooleanField(default=False)),
                ('show_in_list', models.BooleanField(default=True)),
                ('unread_count', models.IntegerField(default=0)),
                ('last_read_sequence', models.BigIntegerField(default=0)),
                ('last_delivered_sequence', models.BigIntegerField(default=0)),
                ('extra_settings', models.JSONField(blank=True, default=dict)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='chat.chatconversation')),
                ('removed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='removed_chat_members', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_memberships', to=settings.AUTH_USER_MODEL)),
                ('last_delivered_message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='chat.chatmessage')),
                ('last_read_message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='chat.chatmessage')),
            ],
            options={
                'db_table': 'chat_conversation_member',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='chatconversation',
            name='last_message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='chat.chatmessage'),
        ),
        migrations.AddIndex(
            model_name='chatfriendrequest',
            index=models.Index(fields=['from_user', 'status', 'created_at'], name='chat_friend_from_us_5615d4_idx'),
        ),
        migrations.AddIndex(
            model_name='chatfriendrequest',
            index=models.Index(fields=['to_user', 'status', 'created_at'], name='chat_friend_to_user_6f5fd6_idx'),
        ),
        migrations.AddIndex(
            model_name='chatfriendrequest',
            index=models.Index(fields=['pair_key', 'status', 'created_at'], name='chat_friend_pair_ke_bd24cc_idx'),
        ),
        migrations.AddIndex(
            model_name='chatfriendrequest',
            index=models.Index(fields=['from_user', 'to_user', 'status'], name='chat_friend_from_us_e565b4_idx'),
        ),
        migrations.AddIndex(
            model_name='chatfriendship',
            index=models.Index(fields=['user_low', 'status'], name='chat_friend_user_lo_2b86f8_idx'),
        ),
        migrations.AddIndex(
            model_name='chatfriendship',
            index=models.Index(fields=['user_high', 'status'], name='chat_friend_user_hi_b5ef69_idx'),
        ),
        migrations.AddIndex(
            model_name='chatgroupconfig',
            index=models.Index(fields=['join_approval_required'], name='chat_group__join_ap_0c8a1d_idx'),
        ),
        migrations.AddIndex(
            model_name='chatgroupjoinrequest',
            index=models.Index(fields=['conversation', 'status', 'created_at'], name='chat_group__convers_4680d6_idx'),
        ),
        migrations.AddIndex(
            model_name='chatgroupjoinrequest',
            index=models.Index(fields=['target_user', 'status', 'created_at'], name='chat_group__target__06c9f0_idx'),
        ),
        migrations.AddIndex(
            model_name='chatgroupjoinrequest',
            index=models.Index(fields=['inviter', 'status', 'created_at'], name='chat_group__inviter_02dfaf_idx'),
        ),
        migrations.AddIndex(
            model_name='chatgroupjoinrequest',
            index=models.Index(fields=['conversation', 'target_user', 'status'], name='chat_group__convers_9e8dc4_idx'),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['conversation', 'created_at'], name='chat_messag_convers_3154fc_idx'),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['conversation', 'id'], name='chat_messag_convers_0a488e_idx'),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['sender', 'created_at'], name='chat_messag_sender__b02346_idx'),
        ),
        migrations.AddConstraint(
            model_name='chatmessage',
            constraint=models.UniqueConstraint(fields=('conversation', 'sequence'), name='uniq_chat_message_conversation_sequence'),
        ),
        migrations.AddIndex(
            model_name='chatconversationmember',
            index=models.Index(fields=['user', 'status', 'updated_at'], name='chat_conver_user_id_46974c_idx'),
        ),
        migrations.AddIndex(
            model_name='chatconversationmember',
            index=models.Index(fields=['user', 'show_in_list', 'updated_at'], name='chat_conver_user_id_3c65c2_idx'),
        ),
        migrations.AddIndex(
            model_name='chatconversationmember',
            index=models.Index(fields=['conversation', 'status', 'role'], name='chat_conver_convers_dcb3f5_idx'),
        ),
        migrations.AddIndex(
            model_name='chatconversationmember',
            index=models.Index(fields=['conversation', 'unread_count'], name='chat_conver_convers_5f6a00_idx'),
        ),
        migrations.AddConstraint(
            model_name='chatconversationmember',
            constraint=models.UniqueConstraint(fields=('conversation', 'user'), name='uniq_chat_conversation_member'),
        ),
        migrations.AddIndex(
            model_name='chatconversation',
            index=models.Index(fields=['type', 'status', 'updated_at'], name='chat_conver_type_f8c3f9_idx'),
        ),
        migrations.AddIndex(
            model_name='chatconversation',
            index=models.Index(fields=['owner', 'status', 'updated_at'], name='chat_conver_owner_i_9d59cb_idx'),
        ),
        migrations.AddIndex(
            model_name='chatconversation',
            index=models.Index(fields=['last_message_at'], name='chat_conver_last_me_f07e7c_idx'),
        ),
        migrations.AddIndex(
            model_name='chatconversation',
            index=models.Index(fields=['name'], name='chat_conver_name_91622c_idx'),
        ),
    ]
