# Generated by Django 5.2 on 2026-04-02 06:56

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GameBestRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('game_code', models.CharField(db_index=True, max_length=64, verbose_name='游戏编码')),
                ('game_name', models.CharField(blank=True, default='', max_length=100, verbose_name='游戏名称')),
                ('best_score', models.PositiveIntegerField(default=0, verbose_name='最高分')),
                ('board_snapshot', models.JSONField(blank=True, default=list, verbose_name='结束棋盘快照')),
                ('finished_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='达成时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_best_records', to=settings.AUTH_USER_MODEL, verbose_name='所属用户')),
            ],
            options={
                'db_table': 'game_best_record',
                'ordering': ['-best_score', 'finished_at', 'id'],
                'indexes': [models.Index(fields=['game_code', '-best_score', 'finished_at'], name='game_best_r_game_co_71b9f4_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'game_code'), name='uniq_game_best_record_user_game')],
            },
        ),
    ]
