# Generated by Django 5.2 on 2026-03-30 10:35

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_user_managers_permission_deleted_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('action', models.CharField(choices=[('login', '登录'), ('create', '创建'), ('update', '更新'), ('delete', '删除'), ('kickout', '踢下线'), ('protect_block', '保护拦截')], max_length=32, verbose_name='动作')),
                ('target_type', models.CharField(blank=True, default='', max_length=64, verbose_name='目标类型')),
                ('target_id', models.CharField(blank=True, default='', max_length=64, verbose_name='目标ID')),
                ('target_repr', models.CharField(blank=True, default='', max_length=255, verbose_name='目标摘要')),
                ('status', models.CharField(choices=[('success', '成功'), ('failed', '失败'), ('blocked', '阻止')], default='success', max_length=16, verbose_name='结果')),
                ('detail', models.CharField(blank=True, default='', max_length=500, verbose_name='详细信息')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='附加数据')),
                ('ip_address', models.CharField(blank=True, default='', max_length=64, verbose_name='IP地址')),
                ('user_agent', models.CharField(blank=True, default='', max_length=500, verbose_name='User-Agent')),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='操作人')),
            ],
            options={
                'db_table': 'audit_log',
                'ordering': ['-id'],
            },
        ),
    ]
