# Generated by Django 5.2 on 2026-04-07 13:15

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auditlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme_mode', models.CharField(default='light', max_length=20, verbose_name='主题模式')),
                ('chat_receive_notification', models.BooleanField(default=True, verbose_name='接收聊天通知')),
                ('chat_list_sort_mode', models.CharField(default='recent', max_length=20, verbose_name='聊天列表排序模式')),
                ('chat_stealth_inspect_enabled', models.BooleanField(default=False, verbose_name='超级管理员隐身巡检开关')),
                ('settings_json', models.JSONField(blank=True, default=dict, verbose_name='扩展设置')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preference', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'db_table': 'user_preference',
                'ordering': ['id'],
                'indexes': [models.Index(fields=['chat_stealth_inspect_enabled'], name='user_prefer_chat_st_1aa66e_idx')],
            },
        ),
    ]
