# Generated by Django 5.2 on 2026-04-22 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hyself', '0007_rename_tables_for_hyself'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='asset',
            new_name='hyself_asse_media_t_0d4272_idx',
            old_name='asset_media_t_919618_idx',
        ),
        migrations.RenameIndex(
            model_name='assetreference',
            new_name='hyself_asse_owner_u_ce23fe_idx',
            old_name='asset_refer_owner_u_baf05f_idx',
        ),
        migrations.RenameIndex(
            model_name='assetreference',
            new_name='hyself_asse_ref_dom_ce466e_idx',
            old_name='asset_refer_ref_dom_adc0be_idx',
        ),
        migrations.RenameIndex(
            model_name='assetreference',
            new_name='hyself_asse_asset_i_8538ed_idx',
            old_name='asset_refer_asset_i_22f9e8_idx',
        ),
        migrations.RenameIndex(
            model_name='uploadedfile',
            new_name='hyself_uplo_created_44779e_idx',
            old_name='uploaded_fi_created_3a1c45_idx',
        ),
        migrations.RenameIndex(
            model_name='uploadedfile',
            new_name='hyself_uplo_created_b3e829_idx',
            old_name='uploaded_fi_created_323e0f_idx',
        ),
    ]
